### ISSUE TITLE
Topページにおける仕様策定

### ISSUE THREAD

**Issue by i35-267** [readhub-inc/readhub_backlog#10]
### Doneの定義
- 画面遷移図 (URL遷移など)
- フロントからAPIコールがある場合には、どういったリクエストパラメーターが必要かなどAPI仕様書が作成されていること

**Comment by KaishiNishimura** [comment]
https://readhub.jp/invites/{inviteId}にアクセス
・ローディング画面
・Firebase Cloud Firestoreのinvites/{inviteId}を取得
　　1. レスポンスの中身がからだった場合
　　　　→エラーページへリダイレクト
　　2.サクセス
　　　　→ローディング終了、ページを表示

Facebookでログインを押したら
・Firebase Authenticationによるログイン処理
　1. エラー
　　→エラーページへリダイレクト
　2. サクセス
　　→詳細登録ページへリダイレクト
