### ISSUE TITLE
技術選定 : FirebaseでMVP機能のバックエンド側を担保できるか

### ISSUE THREAD

**Issue by i35-267** [readhub-inc/readhub_backlog#11]
### Doneの定義
- EpicにあるMVP1~7個のバックエンド側がFirebaseで包含できるかが調査されていること
- MVPの中でできるものできないもののマッピング表が作成されていること。

### 参考資料
 ![スクリーンショット 2019-04-16 2.25.58.png](https://images.zenhubusercontent.com/5b5f2d85f2dac06801e9e07b/ed82e71b-f851-4bf7-9c97-67efbe165bd9)

**Comment by KaishiNishimura** [comment]
|MVP |実装  |備考  |
|---|---|---|
|1  |○ |特になし  |
|2  |○ |特になし  |
|3  |○ |特になし  |
|4  |△ |いいね、コメントはできるが、取得が問題。ある投稿にいいね・コメントした人のプロフィールを取得するには、①いいね・コメントをした人の分だけ通信する、もしくは、②全ユーザーのプロフィールを取得後、いいね・コメントした人のみフィルターする必要がある。(他にも非正規化して保存できるが、ユーザーのプロフィール情報が反映されない)  |
|5  |○ |取得時、データベースにアクセスするか、Amazon APIにアクセスするか。Amazon APIに毎回アクセスする場合本一冊ずつ行う必要がある(アクセスリミットがあるため、ユーザーが増えた場合、非現実的)。データベースにアクセスする場合、同じように一冊ずつ取ってくるか、データベースに保存された本をすべて取ってきて、フィルターする必要がある。もしくは非正規化して保存する。(処理的には楽)  |
|6  |○ |特になし  |
|7  |○ |特になし  |
