### ISSUE TITLE
ローカル開発環境構築手順の作成

### ISSUE THREAD

**Issue by i35-267** [readhub-inc/readhub_backlog#15]
### Doneの定義
- ローカル開発環境が立ち上がり、開発中のReadHubページが閲覧できること。

### 特記事項
- いまあるREADMEを厚めに説明を加える形で良いと思います。Firebaseでもやることがあればそれも追記お願いします。
- https://github.com/readhub-inc/readhub-web-application

**Comment by nkpoid** [comment]
![image](https://user-images.githubusercontent.com/7278829/56854086-0901ad00-696c-11e9-9324-e22fb9ed81df.png)
とりあえずはビルド成功して動きました, fb permissionの問題で認証後画面見れませんが…
あと原因特定はしてませんが、node v12.0.0だとbuildコケますね
