### ISSUE TITLE
ローカル開発環境構築（渡辺）

### ISSUE THREAD

**Issue by i35-267** [readhub-inc/readhub_backlog#16]
### Doneの定義
- #15で作成した手順書をもとにReadHubのローカル環境が立ち上げって閲覧可能になっていること。

### 参考資料
- #15

**Comment by nkpoid** [comment]
申し訳ない、深夜で頭が死んでて https://github.com/readhub-inc/readhub_backlog/issues/15#issuecomment-487312218 の貼る場所を間違えました
